const data = {
    "data": {
        "overall": [
            {
                "apps": 1,
                "assists": 0,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506.png?lm=1594291454",
                "goals": 1,
                "league": "Supercoppa Italiana",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/sci.png?lm=1576764644",
                "minutes_goal": 90,
                "minutes_played": 90,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "20/21",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 14,
                "assists": 1,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506.png?lm=1594291454",
                "goals": 15,
                "league": "Serie A",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/it1.png?lm=1562052084",
                "minutes_goal": 79,
                "minutes_played": 1182,
                "own_goal": 0,
                "penalty_goal": 4,
                "ppg": "2.14",
                "red_card": 0,
                "season": "20/21",
                "second_yellow_card": 0,
                "squads": 14,
                "substitutions_off": 2,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506.png?lm=1594291454",
                "goals": 0,
                "league": "Coppa Italia",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cit.png?lm=1599831579",
                "minutes_goal": 0,
                "minutes_played": 32,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "20/21",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 4,
                "assists": 1,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506.png?lm=1594291454",
                "goals": 4,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 90,
                "minutes_played": 360,
                "own_goal": 0,
                "penalty_goal": 2,
                "ppg": "3.00",
                "red_card": 0,
                "season": "20/21",
                "second_yellow_card": 0,
                "squads": 4,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 8,
                "assists": 1,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506.png?lm=1594291454",
                "goals": 4,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 178,
                "minutes_played": 712,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "2.38",
                "red_card": 0,
                "season": "19/20",
                "second_yellow_card": 0,
                "squads": 8,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 33,
                "assists": 6,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506.png?lm=1594291454",
                "goals": 31,
                "league": "Serie A",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/it1.png?lm=1562052084",
                "minutes_goal": 94,
                "minutes_played": 2919,
                "own_goal": 0,
                "penalty_goal": 12,
                "ppg": "2.21",
                "red_card": 0,
                "season": "19/20",
                "second_yellow_card": 0,
                "squads": 33,
                "substitutions_off": 2,
                "substitutions_on": 0,
                "yellow_card": 3
            },
            {
                "apps": 4,
                "assists": 0,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506.png?lm=1594291454",
                "goals": 2,
                "league": "Coppa Italia",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cit_1532943336.png?lm=1532943336",
                "minutes_goal": 180,
                "minutes_played": 360,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "1.25",
                "red_card": 0,
                "season": "19/20",
                "second_yellow_card": 0,
                "squads": 4,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506.png?lm=1594291454",
                "goals": 0,
                "league": "Supercoppa Italiana",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/sci.png?lm=1576764644",
                "minutes_goal": 0,
                "minutes_played": 90,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0,00",
                "red_card": 0,
                "season": "19/20",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 31,
                "assists": 9,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506_1539955489.png?lm=1539955489",
                "goals": 21,
                "league": "Serie A",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/it1_1562052035.png?lm=1562052035",
                "minutes_goal": 128,
                "minutes_played": 2689,
                "own_goal": 0,
                "penalty_goal": 5,
                "ppg": "2.52",
                "red_card": 0,
                "season": "18/19",
                "second_yellow_card": 0,
                "squads": 32,
                "substitutions_off": 2,
                "substitutions_on": 1,
                "yellow_card": 3
            },
            {
                "apps": 9,
                "assists": 2,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506_1539955489.png?lm=1539955489",
                "goals": 6,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 125,
                "minutes_played": 749,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "1.44",
                "red_card": 1,
                "season": "18/19",
                "second_yellow_card": 0,
                "squads": 9,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506_1539955489.png?lm=1539955489",
                "goals": 0,
                "league": "Coppa Italia",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cit_1532943336.png?lm=1532943336",
                "minutes_goal": 0,
                "minutes_played": 118,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.50",
                "red_card": 0,
                "season": "18/19",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Juventus FC",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/506_1539955489.png?lm=1539955489",
                "goals": 1,
                "league": "Supercoppa Italiana",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/sci_1576761772.png?lm=1576761772",
                "minutes_goal": 90,
                "minutes_played": 90,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "18/19",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 13,
                "assists": 3,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 15,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 78,
                "minutes_played": 1170,
                "own_goal": 0,
                "penalty_goal": 4,
                "ppg": "2.23",
                "red_card": 0,
                "season": "17/18",
                "second_yellow_card": 0,
                "squads": 13,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 2
            },
            {
                "apps": 27,
                "assists": 5,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 26,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1.png?lm=1557051003",
                "minutes_goal": 88,
                "minutes_played": 2297,
                "own_goal": 0,
                "penalty_goal": 3,
                "ppg": "1.96",
                "red_card": 0,
                "season": "17/18",
                "second_yellow_card": 0,
                "squads": 27,
                "substitutions_off": 7,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 2,
                "league": "FIFA Club World Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/klub.png?lm=1520607013",
                "minutes_goal": 90,
                "minutes_played": 180,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "17/18",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 1,
                "league": "Supercopa",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/suc.png?lm=1520607013",
                "minutes_goal": 24,
                "minutes_played": 24,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "17/18",
                "second_yellow_card": 1,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 0,
                "league": "UEFA Super Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/usc.png?lm=1520607013",
                "minutes_goal": 0,
                "minutes_played": 7,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "17/18",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 13,
                "assists": 6,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 12,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 100,
                "minutes_played": 1200,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "2.31",
                "red_card": 0,
                "season": "16/17",
                "second_yellow_card": 0,
                "squads": 13,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 29,
                "assists": 6,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 25,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1.png?lm=1557051003",
                "minutes_goal": 102,
                "minutes_played": 2544,
                "own_goal": 0,
                "penalty_goal": 6,
                "ppg": "2.28",
                "red_card": 0,
                "season": "16/17",
                "second_yellow_card": 0,
                "squads": 29,
                "substitutions_off": 5,
                "substitutions_on": 0,
                "yellow_card": 4
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 1,
                "league": "Copa del Rey",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cdr.png?lm=1520607012",
                "minutes_goal": 180,
                "minutes_played": 180,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0.50",
                "red_card": 0,
                "season": "16/17",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 4,
                "league": "FIFA Club World Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/klub.png?lm=1520607013",
                "minutes_goal": 51,
                "minutes_played": 202,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "3.00",
                "red_card": 0,
                "season": "16/17",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 12,
                "assists": 4,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 16,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 69,
                "minutes_played": 1109,
                "own_goal": 0,
                "penalty_goal": 2,
                "ppg": "2.58",
                "red_card": 0,
                "season": "15/16",
                "second_yellow_card": 0,
                "squads": 12,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 36,
                "assists": 11,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 35,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1_1467208088.png?lm=1467208088",
                "minutes_goal": 91,
                "minutes_played": 3184,
                "own_goal": 0,
                "penalty_goal": 6,
                "ppg": "2.33",
                "red_card": 0,
                "season": "15/16",
                "second_yellow_card": 0,
                "squads": 36,
                "substitutions_off": 3,
                "substitutions_on": 0,
                "yellow_card": 2
            },
            {
                "apps": 35,
                "assists": 17,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 48,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1_1467208088.png?lm=1467208088",
                "minutes_goal": 65,
                "minutes_played": 3099,
                "own_goal": 0,
                "penalty_goal": 10,
                "ppg": "2.46",
                "red_card": 1,
                "season": "14/15",
                "second_yellow_card": 0,
                "squads": 35,
                "substitutions_off": 3,
                "substitutions_on": 0,
                "yellow_card": 4
            },
            {
                "apps": 12,
                "assists": 4,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 10,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 107,
                "minutes_played": 1065,
                "own_goal": 0,
                "penalty_goal": 3,
                "ppg": "2.17",
                "red_card": 0,
                "season": "14/15",
                "second_yellow_card": 0,
                "squads": 12,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 1,
                "league": "Copa del Rey",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cdr.png?lm=1520607012",
                "minutes_goal": 117,
                "minutes_played": 117,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0.50",
                "red_card": 0,
                "season": "14/15",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 2,
                "assists": 2,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 0,
                "league": "FIFA Club World Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/klub.png?lm=1520607013",
                "minutes_goal": 0,
                "minutes_played": 180,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "14/15",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 0,
                "league": "Supercopa",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/suc.png?lm=1520607013",
                "minutes_goal": 0,
                "minutes_played": 89,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0.50",
                "red_card": 0,
                "season": "14/15",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 1
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 2,
                "league": "UEFA Super Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/usc.png?lm=1520607013",
                "minutes_goal": 45,
                "minutes_played": 90,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "14/15",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 11,
                "assists": 5,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 17,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 58,
                "minutes_played": 993,
                "own_goal": 0,
                "penalty_goal": 2,
                "ppg": "2.82",
                "red_card": 0,
                "season": "13/14",
                "second_yellow_card": 0,
                "squads": 12,
                "substitutions_off": 2,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 30,
                "assists": 11,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 31,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1_1467208088.png?lm=1467208088",
                "minutes_goal": 82,
                "minutes_played": 2540,
                "own_goal": 0,
                "penalty_goal": 6,
                "ppg": "2.20",
                "red_card": 1,
                "season": "13/14",
                "second_yellow_card": 0,
                "squads": 30,
                "substitutions_off": 3,
                "substitutions_on": 0,
                "yellow_card": 4
            },
            {
                "apps": 6,
                "assists": 1,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 3,
                "league": "Copa del Rey",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cdr.png?lm=1520607012",
                "minutes_goal": 166,
                "minutes_played": 497,
                "own_goal": 0,
                "penalty_goal": 2,
                "ppg": "3.00",
                "red_card": 0,
                "season": "13/14",
                "second_yellow_card": 0,
                "squads": 6,
                "substitutions_off": 2,
                "substitutions_on": 0,
                "yellow_card": 2
            },
            {
                "apps": 7,
                "assists": 1,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 7,
                "league": "Copa del Rey",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cdr.png?lm=1520607012",
                "minutes_goal": 94,
                "minutes_played": 655,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "1.57",
                "red_card": 1,
                "season": "12/13",
                "second_yellow_card": 0,
                "squads": 8,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 3
            },
            {
                "apps": 34,
                "assists": 11,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 34,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1_1467208088.png?lm=1467208088",
                "minutes_goal": 80,
                "minutes_played": 2716,
                "own_goal": 1,
                "penalty_goal": 6,
                "ppg": "2.26",
                "red_card": 0,
                "season": "12/13",
                "second_yellow_card": 0,
                "squads": 34,
                "substitutions_off": 5,
                "substitutions_on": 4,
                "yellow_card": 9
            },
            {
                "apps": 12,
                "assists": 1,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 12,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 90,
                "minutes_played": 1080,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.75",
                "red_card": 0,
                "season": "12/13",
                "second_yellow_card": 0,
                "squads": 12,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 2,
                "league": "Supercopa",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/suc.png?lm=1520607013",
                "minutes_goal": 90,
                "minutes_played": 180,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.50",
                "red_card": 0,
                "season": "12/13",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 38,
                "assists": 12,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 46,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1_1467208088.png?lm=1467208088",
                "minutes_goal": 73,
                "minutes_played": 3354,
                "own_goal": 0,
                "penalty_goal": 12,
                "ppg": "2.63",
                "red_card": 0,
                "season": "11/12",
                "second_yellow_card": 0,
                "squads": 38,
                "substitutions_off": 2,
                "substitutions_on": 1,
                "yellow_card": 4
            },
            {
                "apps": 10,
                "assists": 3,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 10,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 93,
                "minutes_played": 930,
                "own_goal": 0,
                "penalty_goal": 2,
                "ppg": "2.20",
                "red_card": 0,
                "season": "11/12",
                "second_yellow_card": 0,
                "squads": 11,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 5,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 3,
                "league": "Copa del Rey",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cdr.png?lm=1520607012",
                "minutes_goal": 146,
                "minutes_played": 438,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "2.00",
                "red_card": 0,
                "season": "11/12",
                "second_yellow_card": 0,
                "squads": 5,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 1,
                "league": "Supercopa",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/suc.png?lm=1520607013",
                "minutes_goal": 180,
                "minutes_played": 180,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0.50",
                "red_card": 0,
                "season": "11/12",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 34,
                "assists": 13,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 40,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1_1467208088.png?lm=1467208088",
                "minutes_goal": 73,
                "minutes_played": 2913,
                "own_goal": 0,
                "penalty_goal": 8,
                "ppg": "2.53",
                "red_card": 0,
                "season": "10/11",
                "second_yellow_card": 0,
                "squads": 34,
                "substitutions_off": 1,
                "substitutions_on": 2,
                "yellow_card": 2
            },
            {
                "apps": 12,
                "assists": 4,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 6,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 170,
                "minutes_played": 1021,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "2.25",
                "red_card": 0,
                "season": "10/11",
                "second_yellow_card": 0,
                "squads": 12,
                "substitutions_off": 3,
                "substitutions_on": 0,
                "yellow_card": 2
            },
            {
                "apps": 8,
                "assists": 1,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 7,
                "league": "Copa del Rey",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cdr.png?lm=1520607012",
                "minutes_goal": 98,
                "minutes_played": 684,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "2.75",
                "red_card": 0,
                "season": "10/11",
                "second_yellow_card": 0,
                "squads": 8,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 3
            },
            {
                "apps": 29,
                "assists": 10,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 26,
                "league": "LaLiga",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/es1_1467208088.png?lm=1467208088",
                "minutes_goal": 95,
                "minutes_played": 2465,
                "own_goal": 0,
                "penalty_goal": 4,
                "ppg": "2.55",
                "red_card": 1,
                "season": "09/10",
                "second_yellow_card": 1,
                "squads": 29,
                "substitutions_off": 4,
                "substitutions_on": 1,
                "yellow_card": 3
            },
            {
                "apps": 6,
                "assists": 1,
                "club": "Real Madrid",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/418.png?lm=1580722449",
                "goals": 7,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 64,
                "minutes_played": 450,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "2.17",
                "red_card": 0,
                "season": "09/10",
                "second_yellow_card": 0,
                "squads": 6,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 12,
                "assists": 3,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 4,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 253,
                "minutes_played": 1010,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.92",
                "red_card": 0,
                "season": "08/09",
                "second_yellow_card": 0,
                "squads": 12,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 2
            },
            {
                "apps": 33,
                "assists": 7,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 18,
                "league": "Premier League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/gb1_1464786857.png?lm=1464786857",
                "minutes_goal": 153,
                "minutes_played": 2745,
                "own_goal": 0,
                "penalty_goal": 4,
                "ppg": "2.42",
                "red_card": 0,
                "season": "08/09",
                "second_yellow_card": 1,
                "squads": 34,
                "substitutions_off": 5,
                "substitutions_on": 2,
                "yellow_card": 5
            },
            {
                "apps": 4,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 2,
                "league": "EFL Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cgb_1470748676.png?lm=1470748676",
                "minutes_goal": 120,
                "minutes_played": 240,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "2.25",
                "red_card": 0,
                "season": "08/09",
                "second_yellow_card": 0,
                "squads": 4,
                "substitutions_off": 1,
                "substitutions_on": 2,
                "yellow_card": 1
            },
            {
                "apps": 2,
                "assists": 1,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 1,
                "league": "FA Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/fac_1518123772.png?lm=1518123772",
                "minutes_goal": 144,
                "minutes_played": 144,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "08/09",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 2,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 2,
                "assists": 1,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 1,
                "league": "FIFA Club World Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/klub.png?lm=1520607013",
                "minutes_goal": 180,
                "minutes_played": 180,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "08/09",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 11,
                "assists": 1,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 8,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 127,
                "minutes_played": 1017,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "2.64",
                "red_card": 0,
                "season": "07/08",
                "second_yellow_card": 0,
                "squads": 12,
                "substitutions_off": 2,
                "substitutions_on": 0,
                "yellow_card": 2
            },
            {
                "apps": 34,
                "assists": 7,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 31,
                "league": "Premier League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/gb1_1464786857.png?lm=1464786857",
                "minutes_goal": 89,
                "minutes_played": 2747,
                "own_goal": 0,
                "penalty_goal": 4,
                "ppg": "2.38",
                "red_card": 1,
                "season": "07/08",
                "second_yellow_card": 0,
                "squads": 34,
                "substitutions_off": 4,
                "substitutions_on": 3,
                "yellow_card": 5
            },
            {
                "apps": 3,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 3,
                "league": "FA Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/fac_1518123772.png?lm=1518123772",
                "minutes_goal": 90,
                "minutes_played": 270,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "2.00",
                "red_card": 0,
                "season": "07/08",
                "second_yellow_card": 0,
                "squads": 3,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "Community Shield",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/gbcs.png?lm=1470391655",
                "minutes_goal": 0,
                "minutes_played": 120,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "07/08",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 7,
                "assists": 1,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 3,
                "league": "FA Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/fac_1518123772.png?lm=1518123772",
                "minutes_goal": 186,
                "minutes_played": 558,
                "own_goal": 0,
                "penalty_goal": 2,
                "ppg": "2.00",
                "red_card": 0,
                "season": "06/07",
                "second_yellow_card": 0,
                "squads": 7,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 34,
                "assists": 15,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 17,
                "league": "Premier League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/gb1_1464786646.png?lm=1464786646",
                "minutes_goal": 164,
                "minutes_played": 2787,
                "own_goal": 0,
                "penalty_goal": 3,
                "ppg": "2.32",
                "red_card": 0,
                "season": "06/07",
                "second_yellow_card": 0,
                "squads": 34,
                "substitutions_off": 11,
                "substitutions_on": 3,
                "yellow_card": 2
            },
            {
                "apps": 11,
                "assists": 5,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 3,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 317,
                "minutes_played": 951,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.91",
                "red_card": 0,
                "season": "06/07",
                "second_yellow_card": 0,
                "squads": 11,
                "substitutions_off": 2,
                "substitutions_on": 0,
                "yellow_card": 3
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "EFL Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cgb_1470748676.png?lm=1470748676",
                "minutes_goal": 0,
                "minutes_played": 90,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0,00",
                "red_card": 0,
                "season": "06/07",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 33,
                "assists": 7,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 9,
                "league": "Premier League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/gb1_1464786646.png?lm=1464786646",
                "minutes_goal": 254,
                "minutes_played": 2286,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "2.12",
                "red_card": 1,
                "season": "05/06",
                "second_yellow_card": 0,
                "squads": 33,
                "substitutions_off": 10,
                "substitutions_on": 9,
                "yellow_card": 8
            },
            {
                "apps": 4,
                "assists": 1,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 2,
                "league": "EFL Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cgb_1470748676.png?lm=1470748676",
                "minutes_goal": 172,
                "minutes_played": 343,
                "own_goal": 0,
                "penalty_goal": 1,
                "ppg": "2.50",
                "red_card": 0,
                "season": "05/06",
                "second_yellow_card": 0,
                "squads": 4,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "FA Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/fac_1518123772.png?lm=1518123772",
                "minutes_goal": 0,
                "minutes_played": 121,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0.50",
                "red_card": 0,
                "season": "05/06",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 6,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 0,
                "minutes_played": 506,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.00",
                "red_card": 0,
                "season": "05/06",
                "second_yellow_card": 0,
                "squads": 6,
                "substitutions_off": 3,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 2,
                "assists": 1,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 1,
                "league": "UEFA Champions League Qualifying",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/clq.png?lm=1520607012",
                "minutes_goal": 157,
                "minutes_played": 157,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "05/06",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 7,
                "assists": 3,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 4,
                "league": "FA Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/fac_1518123772.png?lm=1518123772",
                "minutes_goal": 136,
                "minutes_played": 545,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "2.29",
                "red_card": 0,
                "season": "04/05",
                "second_yellow_card": 0,
                "squads": 7,
                "substitutions_off": 3,
                "substitutions_on": 1,
                "yellow_card": 1
            },
            {
                "apps": 33,
                "assists": 4,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 5,
                "league": "Premier League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/gb1_1464786646.png?lm=1464786646",
                "minutes_goal": 485,
                "minutes_played": 2425,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.97",
                "red_card": 0,
                "season": "04/05",
                "second_yellow_card": 0,
                "squads": 33,
                "substitutions_off": 9,
                "substitutions_on": 8,
                "yellow_card": 3
            },
            {
                "apps": 7,
                "assists": 2,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 0,
                "minutes_played": 502,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.14",
                "red_card": 0,
                "season": "04/05",
                "second_yellow_card": 0,
                "squads": 8,
                "substitutions_off": 2,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "EFL Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cgb_1470748676.png?lm=1470748676",
                "minutes_goal": 0,
                "minutes_played": 180,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0.50",
                "red_card": 0,
                "season": "04/05",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "UEFA Champions League Qualifying",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/clq.png?lm=1520607012",
                "minutes_goal": 0,
                "minutes_played": 64,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "04/05",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 5,
                "assists": 4,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 2,
                "league": "FA Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/fac_1518123772.png?lm=1518123772",
                "minutes_goal": 218,
                "minutes_played": 436,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "3.00",
                "red_card": 0,
                "season": "03/04",
                "second_yellow_card": 0,
                "squads": 5,
                "substitutions_off": 3,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 29,
                "assists": 4,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 4,
                "league": "Premier League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/gb1_1464786592.png?lm=1464786593",
                "minutes_goal": 388,
                "minutes_played": 1551,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.97",
                "red_card": 0,
                "season": "03/04",
                "second_yellow_card": 1,
                "squads": 32,
                "substitutions_off": 6,
                "substitutions_on": 14,
                "yellow_card": 3
            },
            {
                "apps": 5,
                "assists": 1,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "UEFA Champions League",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cl.png?lm=1520874127",
                "minutes_goal": 0,
                "minutes_played": 291,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.40",
                "red_card": 0,
                "season": "03/04",
                "second_yellow_card": 0,
                "squads": 7,
                "substitutions_off": 2,
                "substitutions_on": 2,
                "yellow_card": 0
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Manchester United",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/985.png?lm=1457975903",
                "goals": 0,
                "league": "EFL Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/cgb_1470748676.png?lm=1470748676",
                "minutes_goal": 0,
                "minutes_played": 77,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0,00",
                "red_card": 0,
                "season": "03/04",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 25,
                "assists": 4,
                "club": "Sporting CP",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/336.png?lm=1487424635",
                "goals": 3,
                "league": "Liga NOS",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/po1.png?lm=1485174349",
                "minutes_goal": 356,
                "minutes_played": 1069,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.56",
                "red_card": 0,
                "season": "02/03",
                "second_yellow_card": 0,
                "squads": 30,
                "substitutions_off": 8,
                "substitutions_on": 14,
                "yellow_card": 1
            },
            {
                "apps": 3,
                "assists": 0,
                "club": "Sporting CP",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/336.png?lm=1487424635",
                "goals": 2,
                "league": "Ta\u00e7a de Portugal Placard",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/popo.png?lm=1460151160",
                "minutes_goal": 86,
                "minutes_played": 172,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "2.00",
                "red_card": 0,
                "season": "02/03",
                "second_yellow_card": 0,
                "squads": 3,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 2,
                "assists": 0,
                "club": "Sporting CP",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/336.png?lm=1487424635",
                "goals": 0,
                "league": "UEFA-Cup",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/uefa.png?lm=1401990307",
                "minutes_goal": 0,
                "minutes_played": 118,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "0.50",
                "red_card": 0,
                "season": "02/03",
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 0,
                "assists": 0,
                "club": "Sporting CP",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/336.png?lm=1487424635",
                "goals": 0,
                "league": "Superta\u00e7a C\u00e2ndido de Oliveira",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/posu.png?lm=1470311398",
                "minutes_goal": 0,
                "minutes_played": 0,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": 0,
                "red_card": 0,
                "season": "02/03",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 1,
                "assists": 0,
                "club": "Sporting CP",
                "club_badge": "https://tmssl.akamaized.net/images/wappen/tiny/336.png?lm=1487424635",
                "goals": 0,
                "league": "UEFA Champions League Qualifying",
                "league_badge": "https://tmssl.akamaized.net/images/logo/tiny/clq.png?lm=1520607012",
                "minutes_goal": 0,
                "minutes_played": 32,
                "own_goal": 0,
                "penalty_goal": 0,
                "ppg": "1.00",
                "red_card": 0,
                "season": "02/03",
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 1,
                "yellow_card": 0
            }
        ],
        "player_bio": {
            "agent": "Gestifute",
            "birth": "Feb 5, 1985",
            "birth_country": "Portugal",
            "birth_place": "Funchal",
            "citizenship": "Portugal",
            "contract_expires": "Jun 30, 2022",
            "current_international": "Portugal",
            "height": "1,87 m",
            "international_performance": {
                "apps": "170",
                "goals": "102"
            },
            "name": "Cristiano Ronaldo",
            "player_status": "Juventus",
            "position": "Left Winger",
            "profile_image": "https://img.a.transfermarkt.technology/portrait/header/8198-1568120625.jpg?lm=1"
        },
        "stats_by_club": [
            {
                "apps": 109,
                "assists": 20,
                "club": "Juventus FC",
                "goals": 85,
                "minutes_goal": 1054,
                "minutes_played": 9391,
                "own_goal": 0,
                "penalty_goal": 26,
                "red_card": 1,
                "second_yellow_card": 0,
                "squads": 110,
                "substitutions_off": 8,
                "substitutions_on": 4,
                "yellow_card": 8
            },
            {
                "apps": 292,
                "assists": 68,
                "club": "Manchester United",
                "goals": 118,
                "minutes_goal": 3633,
                "minutes_played": 22343,
                "own_goal": 0,
                "penalty_goal": 17,
                "red_card": 2,
                "second_yellow_card": 2,
                "squads": 300,
                "substitutions_off": 72,
                "substitutions_on": 48,
                "yellow_card": 38
            },
            {
                "apps": 438,
                "assists": 132,
                "club": "Real Madrid",
                "goals": 450,
                "minutes_goal": 2859,
                "minutes_played": 37833,
                "own_goal": 1,
                "penalty_goal": 79,
                "red_card": 4,
                "second_yellow_card": 2,
                "squads": 441,
                "substitutions_off": 47,
                "substitutions_on": 14,
                "yellow_card": 54
            },
            {
                "apps": 31,
                "assists": 4,
                "club": "Sporting CP",
                "goals": 5,
                "minutes_goal": 442,
                "minutes_played": 1391,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 37,
                "substitutions_off": 10,
                "substitutions_on": 17,
                "yellow_card": 1
            }
        ],
        "stats_by_league": [
            {
                "apps": 1,
                "assists": 0,
                "goals": 0,
                "league": "Community Shield",
                "minutes_goal": 0,
                "minutes_played": 120,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 30,
                "assists": 3,
                "goals": 22,
                "league": "Copa del Rey",
                "minutes_goal": 801,
                "minutes_played": 2571,
                "own_goal": 0,
                "penalty_goal": 3,
                "red_card": 1,
                "second_yellow_card": 0,
                "squads": 31,
                "substitutions_off": 4,
                "substitutions_on": 2,
                "yellow_card": 9
            },
            {
                "apps": 7,
                "assists": 0,
                "goals": 2,
                "league": "Coppa Italia",
                "minutes_goal": 180,
                "minutes_played": 510,
                "own_goal": 0,
                "penalty_goal": 1,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 7,
                "substitutions_off": 0,
                "substitutions_on": 2,
                "yellow_card": 0
            },
            {
                "apps": 12,
                "assists": 1,
                "goals": 4,
                "league": "EFL Cup",
                "minutes_goal": 292,
                "minutes_played": 930,
                "own_goal": 0,
                "penalty_goal": 2,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 12,
                "substitutions_off": 4,
                "substitutions_on": 2,
                "yellow_card": 3
            },
            {
                "apps": 26,
                "assists": 9,
                "goals": 13,
                "league": "FA Cup",
                "minutes_goal": 774,
                "minutes_played": 2074,
                "own_goal": 0,
                "penalty_goal": 3,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 26,
                "substitutions_off": 9,
                "substitutions_on": 3,
                "yellow_card": 1
            },
            {
                "apps": 8,
                "assists": 3,
                "goals": 7,
                "league": "FIFA Club World Cup",
                "minutes_goal": 321,
                "minutes_played": 742,
                "own_goal": 0,
                "penalty_goal": 1,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 8,
                "substitutions_off": 1,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 292,
                "assists": 96,
                "goals": 311,
                "league": "LaLiga",
                "minutes_goal": 749,
                "minutes_played": 25112,
                "own_goal": 1,
                "penalty_goal": 61,
                "red_card": 3,
                "second_yellow_card": 1,
                "squads": 292,
                "substitutions_off": 33,
                "substitutions_on": 8,
                "yellow_card": 33
            },
            {
                "apps": 25,
                "assists": 4,
                "goals": 3,
                "league": "Liga NOS",
                "minutes_goal": 356,
                "minutes_played": 1069,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 30,
                "substitutions_off": 8,
                "substitutions_on": 14,
                "yellow_card": 1
            },
            {
                "apps": 196,
                "assists": 44,
                "goals": 84,
                "league": "Premier League",
                "minutes_goal": 1533,
                "minutes_played": 14541,
                "own_goal": 0,
                "penalty_goal": 11,
                "red_card": 2,
                "second_yellow_card": 2,
                "squads": 200,
                "substitutions_off": 45,
                "substitutions_on": 39,
                "yellow_card": 26
            },
            {
                "apps": 78,
                "assists": 16,
                "goals": 67,
                "league": "Serie A",
                "minutes_goal": 301,
                "minutes_played": 6790,
                "own_goal": 0,
                "penalty_goal": 21,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 79,
                "substitutions_off": 6,
                "substitutions_on": 2,
                "yellow_card": 6
            },
            {
                "apps": 7,
                "assists": 0,
                "goals": 4,
                "league": "Supercopa",
                "minutes_goal": 294,
                "minutes_played": 473,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 1,
                "squads": 7,
                "substitutions_off": 1,
                "substitutions_on": 2,
                "yellow_card": 2
            },
            {
                "apps": 3,
                "assists": 0,
                "goals": 2,
                "league": "Supercoppa Italiana",
                "minutes_goal": 180,
                "minutes_played": 270,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 3,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 1
            },
            {
                "apps": 0,
                "assists": 0,
                "goals": 0,
                "league": "Superta\u00e7a C\u00e2ndido de Oliveira",
                "minutes_goal": 0,
                "minutes_played": 0,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 1,
                "substitutions_off": 0,
                "substitutions_on": 0,
                "yellow_card": 0
            },
            {
                "apps": 3,
                "assists": 0,
                "goals": 2,
                "league": "Ta\u00e7a de Portugal Placard",
                "minutes_goal": 86,
                "minutes_played": 172,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 3,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 174,
                "assists": 47,
                "goals": 134,
                "league": "UEFA Champions League",
                "minutes_goal": 1919,
                "minutes_played": 15116,
                "own_goal": 0,
                "penalty_goal": 19,
                "red_card": 1,
                "second_yellow_card": 0,
                "squads": 180,
                "substitutions_off": 22,
                "substitutions_on": 5,
                "yellow_card": 19
            },
            {
                "apps": 4,
                "assists": 1,
                "goals": 1,
                "league": "UEFA Champions League Qualifying",
                "minutes_goal": 157,
                "minutes_played": 253,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 4,
                "substitutions_off": 2,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 2,
                "assists": 0,
                "goals": 2,
                "league": "UEFA Super Cup",
                "minutes_goal": 45,
                "minutes_played": 97,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 0,
                "substitutions_on": 1,
                "yellow_card": 0
            },
            {
                "apps": 2,
                "assists": 0,
                "goals": 0,
                "league": "UEFA-Cup",
                "minutes_goal": 0,
                "minutes_played": 118,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "second_yellow_card": 0,
                "squads": 2,
                "substitutions_off": 1,
                "substitutions_on": 1,
                "yellow_card": 0
            }
        ],
        "stats_by_season": [
            {
                "apps": 31,
                "assists": 4,
                "goals": 5,
                "minutes_goal": 442,
                "minutes_played": 1391,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "season": "02/03",
                "second_yellow_card": 0,
                "squads": 37,
                "substitutions_off": 10,
                "substitutions_on": 17,
                "yellow_card": 1
            },
            {
                "apps": 40,
                "assists": 9,
                "goals": 6,
                "minutes_goal": 606,
                "minutes_played": 2355,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "season": "03/04",
                "second_yellow_card": 1,
                "squads": 45,
                "substitutions_off": 12,
                "substitutions_on": 16,
                "yellow_card": 3
            },
            {
                "apps": 50,
                "assists": 9,
                "goals": 9,
                "minutes_goal": 621,
                "minutes_played": 3716,
                "own_goal": 0,
                "penalty_goal": 0,
                "red_card": 0,
                "season": "04/05",
                "second_yellow_card": 0,
                "squads": 51,
                "substitutions_off": 16,
                "substitutions_on": 10,
                "yellow_card": 5
            },
            {
                "apps": 47,
                "assists": 9,
                "goals": 12,
                "minutes_goal": 583,
                "minutes_played": 3413,
                "own_goal": 0,
                "penalty_goal": 1,
                "red_card": 1,
                "season": "05/06",
                "second_yellow_card": 0,
                "squads": 47,
                "substitutions_off": 15,
                "substitutions_on": 10,
                "yellow_card": 10
            },
            {
                "apps": 53,
                "assists": 21,
                "goals": 23,
                "minutes_goal": 667,
                "minutes_played": 4386,
                "own_goal": 0,
                "penalty_goal": 5,
                "red_card": 0,
                "season": "06/07",
                "second_yellow_card": 0,
                "squads": 53,
                "substitutions_off": 14,
                "substitutions_on": 4,
                "yellow_card": 5
            },
            {
                "apps": 49,
                "assists": 8,
                "goals": 42,
                "minutes_goal": 306,
                "minutes_played": 4154,
                "own_goal": 0,
                "penalty_goal": 6,
                "red_card": 1,
                "season": "07/08",
                "second_yellow_card": 0,
                "squads": 50,
                "substitutions_off": 6,
                "substitutions_on": 3,
                "yellow_card": 7
            },
            {
                "apps": 53,
                "assists": 12,
                "goals": 26,
                "minutes_goal": 850,
                "minutes_played": 4319,
                "own_goal": 0,
                "penalty_goal": 5,
                "red_card": 0,
                "season": "08/09",
                "second_yellow_card": 1,
                "squads": 54,
                "substitutions_off": 9,
                "substitutions_on": 5,
                "yellow_card": 8
            },
            {
                "apps": 35,
                "assists": 11,
                "goals": 33,
                "minutes_goal": 159,
                "minutes_played": 2915,
                "own_goal": 0,
                "penalty_goal": 4,
                "red_card": 1,
                "season": "09/10",
                "second_yellow_card": 1,
                "squads": 35,
                "substitutions_off": 5,
                "substitutions_on": 2,
                "yellow_card": 3
            },
            {
                "apps": 54,
                "assists": 18,
                "goals": 53,
                "minutes_goal": 341,
                "minutes_played": 4618,
                "own_goal": 0,
                "penalty_goal": 9,
                "red_card": 0,
                "season": "10/11",
                "second_yellow_card": 0,
                "squads": 54,
                "substitutions_off": 5,
                "substitutions_on": 3,
                "yellow_card": 7
            },
            {
                "apps": 55,
                "assists": 15,
                "goals": 60,
                "minutes_goal": 492,
                "minutes_played": 4902,
                "own_goal": 0,
                "penalty_goal": 14,
                "red_card": 0,
                "season": "11/12",
                "second_yellow_card": 0,
                "squads": 56,
                "substitutions_off": 3,
                "substitutions_on": 1,
                "yellow_card": 7
            },
            {
                "apps": 55,
                "assists": 13,
                "goals": 55,
                "minutes_goal": 354,
                "minutes_played": 4631,
                "own_goal": 1,
                "penalty_goal": 7,
                "red_card": 1,
                "season": "12/13",
                "second_yellow_card": 0,
                "squads": 56,
                "substitutions_off": 5,
                "substitutions_on": 4,
                "yellow_card": 13
            },
            {
                "apps": 47,
                "assists": 17,
                "goals": 51,
                "minutes_goal": 306,
                "minutes_played": 4030,
                "own_goal": 0,
                "penalty_goal": 10,
                "red_card": 1,
                "season": "13/14",
                "second_yellow_card": 0,
                "squads": 48,
                "substitutions_off": 7,
                "substitutions_on": 0,
                "yellow_card": 7
            },
            {
                "apps": 54,
                "assists": 23,
                "goals": 61,
                "minutes_goal": 334,
                "minutes_played": 4640,
                "own_goal": 0,
                "penalty_goal": 13,
                "red_card": 1,
                "season": "14/15",
                "second_yellow_card": 0,
                "squads": 54,
                "substitutions_off": 5,
                "substitutions_on": 2,
                "yellow_card": 6
            },
            {
                "apps": 48,
                "assists": 15,
                "goals": 51,
                "minutes_goal": 160,
                "minutes_played": 4293,
                "own_goal": 0,
                "penalty_goal": 8,
                "red_card": 0,
                "season": "15/16",
                "second_yellow_card": 0,
                "squads": 48,
                "substitutions_off": 4,
                "substitutions_on": 0,
                "yellow_card": 3
            },
            {
                "apps": 46,
                "assists": 12,
                "goals": 42,
                "minutes_goal": 433,
                "minutes_played": 4126,
                "own_goal": 0,
                "penalty_goal": 7,
                "red_card": 0,
                "season": "16/17",
                "second_yellow_card": 0,
                "squads": 46,
                "substitutions_off": 6,
                "substitutions_on": 0,
                "yellow_card": 5
            },
            {
                "apps": 44,
                "assists": 8,
                "goals": 44,
                "minutes_goal": 280,
                "minutes_played": 3678,
                "own_goal": 0,
                "penalty_goal": 7,
                "red_card": 0,
                "season": "17/18",
                "second_yellow_card": 1,
                "squads": 44,
                "substitutions_off": 7,
                "substitutions_on": 2,
                "yellow_card": 3
            },
            {
                "apps": 43,
                "assists": 11,
                "goals": 28,
                "minutes_goal": 343,
                "minutes_played": 3646,
                "own_goal": 0,
                "penalty_goal": 6,
                "red_card": 1,
                "season": "18/19",
                "second_yellow_card": 0,
                "squads": 44,
                "substitutions_off": 2,
                "substitutions_on": 2,
                "yellow_card": 4
            },
            {
                "apps": 46,
                "assists": 7,
                "goals": 37,
                "minutes_goal": 452,
                "minutes_played": 4081,
                "own_goal": 0,
                "penalty_goal": 14,
                "red_card": 0,
                "season": "19/20",
                "second_yellow_card": 0,
                "squads": 46,
                "substitutions_off": 3,
                "substitutions_on": 0,
                "yellow_card": 3
            },
            {
                "apps": 20,
                "assists": 2,
                "goals": 20,
                "minutes_goal": 259,
                "minutes_played": 1664,
                "own_goal": 0,
                "penalty_goal": 6,
                "red_card": 0,
                "season": "20/21",
                "second_yellow_card": 0,
                "squads": 20,
                "substitutions_off": 3,
                "substitutions_on": 2,
                "yellow_card": 1
            }
        ],
        "current_club": {
            "name": "Juventus",
            "club_badge": "https://tmssl.akamaized.net/images/wappen/normal/506.png?lm=1594291454"
        },
    },
    "success": true
}

export default data;